import { ArrowUp, CheckSquare2, Clock3, Flame, PawPrint, Sparkles, Trophy } from 'lucide-react'
import { useWoofy } from '../contexts/WoofyContext'

export function ProgressPage() {
  const { tasks, paws, transactions, pet } = useWoofy()
  return (
    <div className="progress-page page-enter">
      <div className="page-heading-row"><div><span className="page-kicker">OLHE O QUANTO VOCÊ JÁ FEZ</span><h1>Seu progresso</h1><p>Não é sobre perfeição. É sobre cada pequeno passo.</p></div><select className="period-select" defaultValue="week"><option value="week">Esta semana</option><option value="month">Este mês</option></select></div>
      <section className="progress-highlight"><div><span><Sparkles /> MENSAGEM DO {pet.name.toUpperCase()}</span><h2>Você apareceu por você mesmo em 5 dias esta semana.</h2><p>Isso já é algo lindo para comemorar. Continue respeitando seu ritmo.</p></div><div className="progress-trophy"><Trophy /><span>Melhor semana!</span></div></section>
      <div className="progress-stat-grid"><article><span className="stat-icon stat-amber"><CheckSquare2 /></span><small>Tarefas concluídas</small><strong>{tasks.filter((task) => task.completed).length + 16}</strong><span className="positive"><ArrowUp /> 12% esta semana</span></article><article><span className="stat-icon stat-rose"><Flame /></span><small>Hábitos realizados</small><strong>24</strong><span className="positive"><ArrowUp /> 8% esta semana</span></article><article><span className="stat-icon stat-mint"><Clock3 /></span><small>Tempo em foco</small><strong>3h 20</strong><span className="positive"><ArrowUp /> 35 min</span></article><article><span className="stat-icon stat-gold"><PawPrint /></span><small>Patinhas ganhas</small><strong>{paws}</strong><span className="positive"><ArrowUp /> 95 novas</span></article></div>
      <div className="progress-content-grid">
        <section className="chart-card"><div className="card-heading"><div><span>EVOLUÇÃO</span><h2>Tarefas ao longo da semana</h2></div><span className="chart-legend"><i /> Concluídas</span></div><div className="bar-chart"><div className="y-axis"><span>8</span><span>6</span><span>4</span><span>2</span><span>0</span></div>{[3, 5, 4, 7, 6, 2, 1].map((value, index) => <div className="chart-bar" key={index}><span style={{ height: `${value * 11}%` }} className={index === 3 ? 'best' : ''}>{index === 3 && <i>7</i>}</span><small>{['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'][index]}</small></div>)}</div></section>
        <section className="chart-card categories-card"><div className="card-heading"><div><span>DISTRIBUIÇÃO</span><h2>Por categoria</h2></div></div><div className="donut-wrap"><div className="donut"><span><strong>42</strong><small>tarefas</small></span></div><div className="donut-legend"><span><i className="study" /> Estudos <strong>38%</strong></span><span><i className="work" /> Trabalho <strong>27%</strong></span><span><i className="personal" /> Pessoal <strong>20%</strong></span><span><i className="health" /> Saúde <strong>15%</strong></span></div></div></section>
        <section className="chart-card productive-card"><div className="card-heading"><div><span>SEU MELHOR HORÁRIO</span><h2>Quando você rende mais</h2></div></div><div className="productive-time"><span>☀</span><div><strong>Entre 9h e 11h</strong><p>É quando você conclui mais tarefas e mantém sessões de foco mais longas.</p></div></div><div className="heatmap">{Array.from({ length: 28 }).map((_, index) => <i className={`heat-${(index * 7) % 5}`} key={index} />)}</div></section>
        <section className="chart-card rewards-history"><div className="card-heading"><div><span>RECOMPENSAS</span><h2>Patinhas recentes</h2></div></div>{transactions.slice(0, 3).map((transaction) => <div className="transaction-row" key={transaction.id}><span><PawPrint fill="currentColor" /></span><div><strong>{transaction.description}</strong><small>{transaction.date}</small></div><b>+{transaction.amount}</b></div>)}</section>
      </div>
    </div>
  )
}
